/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Faq {
  'question' : string,
  'answer' : string,
  'category' : string,
}
export type FaqId = bigint;
export interface FaqInput {
  'question' : string,
  'answer' : string,
  'category' : string,
}
export interface Ticket {
  'status' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type TicketId = bigint;
export interface TicketInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface TicketUpdateInput { 'status' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFaq' : ActorMethod<[FaqInput], FaqId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFaq' : ActorMethod<[FaqId], undefined>,
  'getAllFaqs' : ActorMethod<[], Array<Faq>>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFaqByCategory' : ActorMethod<[string], Array<Faq>>,
  'getTicket' : ActorMethod<[TicketId], Ticket>,
  'getTicketStatus' : ActorMethod<[TicketId], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFaqs' : ActorMethod<[string], Array<Faq>>,
  'sendMessage' : ActorMethod<[string], string>,
  'submitTicket' : ActorMethod<[TicketInput], TicketId>,
  'updateFaq' : ActorMethod<[FaqId, FaqInput], undefined>,
  'updateTicket' : ActorMethod<[TicketId, TicketUpdateInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];