/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FaqInput = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const FaqId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Faq = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const Ticket = IDL.Record({
  'status' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TicketId = IDL.Nat;
export const TicketInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const TicketUpdateInput = IDL.Record({ 'status' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFaq' : IDL.Func([FaqInput], [FaqId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFaq' : IDL.Func([FaqId], [], []),
  'getAllFaqs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
  'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFaqByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Faq)], ['query']),
  'getTicket' : IDL.Func([TicketId], [Ticket], ['query']),
  'getTicketStatus' : IDL.Func([TicketId], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFaqs' : IDL.Func([IDL.Text], [IDL.Vec(Faq)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'submitTicket' : IDL.Func([TicketInput], [TicketId], []),
  'updateFaq' : IDL.Func([FaqId, FaqInput], [], []),
  'updateTicket' : IDL.Func([TicketId, TicketUpdateInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FaqInput = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const FaqId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Faq = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const Ticket = IDL.Record({
    'status' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TicketId = IDL.Nat;
  const TicketInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const TicketUpdateInput = IDL.Record({ 'status' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFaq' : IDL.Func([FaqInput], [FaqId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFaq' : IDL.Func([FaqId], [], []),
    'getAllFaqs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
    'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFaqByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Faq)], ['query']),
    'getTicket' : IDL.Func([TicketId], [Ticket], ['query']),
    'getTicketStatus' : IDL.Func([TicketId], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFaqs' : IDL.Func([IDL.Text], [IDL.Vec(Faq)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'submitTicket' : IDL.Func([TicketInput], [TicketId], []),
    'updateFaq' : IDL.Func([FaqId, FaqInput], [], []),
    'updateTicket' : IDL.Func([TicketId, TicketUpdateInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };